# Generated by Django 6.0 on 2025-12-12 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
