# Generated by Django 6.0 on 2025-12-12 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_App', '0002_alter_listings_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='listing_images/'),
        ),
    ]
