# Generated by Django 5.2.8 on 2025-12-15 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_App', '0003_listings_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, related_name='bookmarked_by', to='market_App.listings'),
        ),
    ]
