# Generated by Django 6.0 on 2025-12-15 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_App', '0004_student_bookmarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='is_on_campus',
            field=models.BooleanField(default=False),
        ),
    ]
